nodeLinker: node-modules

npmPublishAccess: restricted

npmRegistryServer: "https://registry.npmjs.org/"

npmScopes:
  exodus:
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
