name: Asana

on:
  issues:
    types: [opened, closed, edited]
  pull_request:
    types: [opened, closed, edited]

permissions: {}

jobs:
  link:
    name: Link
    runs-on: ubuntu-latest
    steps:
      - name: Asana Github Link
        uses: ExodusMovement/asana-actions@a530ae1d369389a4f3b4e6c0322782d5ed4d7f96 # 4.4.0
        with:
          asana_token: ${{ secrets.ASANA_TOKEN }}
          workspace: ${{ secrets.ASANA_WORKSPACE_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
