name: Rebase Conflicts

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conflicts:
    name: Check for Conflicts
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        uses: ExodusMovement/actions-label-merge-conflict@main
        with:
          dirtyLabel: 'blocked/needs-rebase'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          commentOnDirty: 'Houston, this is Conflict Bot. We have a conflict. I repeat, we have a conflict. @<%= author %> please rebase. Acknowledge.'
          retryAfter: 45
          removeDirtyComment: true
