name: Merge chain

on:
  pull_request:
    types:
      - labeled
jobs:
  merge-chain:
    timeout-minutes: 10
    if: github.event.label.name == 'action/merge-chain'
    name: Merge the entire chain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge chain
        uses: ExodusMovement/chain-merge-action@master
        with:
          github-token: ${{ secrets.GH_AUTOMATION_PAT }}
          default-branch: master
          skip-release-label: skip-release
