name: Publish
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

env:
  NX_REJECT_UNKNOWN_LOCAL_CACHE: 0

jobs:
  publish:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'publish-on-merge'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ExodusMovement/actions/setup/lerna@65b395a82884455e8dc0cbc32355d8864f1ec30c
        with:
          npm-token: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - uses: ExodusMovement/lerna-release-action/publish@6dc016246588346b8181638a1c093d8c8e14c7f8
        id: publish
        with:
          github-token: ${{ secrets.GH_AUTOMATION_PAT }}
          required-branch-rulesets: 179028
