name: Publish
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  publish:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'publish-on-merge'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ExodusMovement/actions/setup/lerna@v3
        with:
          npm-token: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - uses: ExodusMovement/lerna-release-action/publish@master
        id: publish
        with:
          github-token: ${{ secrets.GH_AUTOMATION_PAT }}
      - uses: ExodusMovement/athena-action@master
        with:
          github-token: ${{ secrets.GH_AUTOMATION_PAT }}
          package-versions: ${{ steps.publish.outputs.published-packages }}
          repositories: '[{ "owner": "ExodusMovement", "name": "exodus-browser", "packageFile": "src/package.json", "installCommand": "yarn install --ignore-engines --cwd src", "npmToken": "${{ secrets.NPM_TOKEN }}" }, { "owner": "ExodusMovement", "name": "exodus-mobile", "packageFile": "src/package.json", "installCommand": "yarn install --ignore-engines --cwd src", "npmToken": "${{ secrets.NPM_TOKEN }}" }, { "owner": "ExodusMovement", "name": "magic-eden", "packageFile": "apps/browser/src/package.json", "installCommand": "yarn install --ignore-engines --cwd src", "npmToken": "${{ secrets.NPM_TOKEN }}" }, { "owner": "ExodusMovement", "name": "magic-eden", "packageFile": "apps/mobile/src/package.json", "installCommand": "yarn install --ignore-engines --cwd src", "npmToken": "${{ secrets.NPM_TOKEN }}" }]'
