name: Valid PR

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  valid-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Validate
        uses: ExodusMovement/soteria-action@04dab36c9d762a04756972f4bb279467adb1a5af
        with:
          validations: conflicting
          conflictingLabel: 'blocked/needs-rebase'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          skipDraft: conflicting
          retryAfterOnConflicting: 45
          removeValidationComments: true
